import "~/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "~/components/NavBar";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Ramirez Tree Service",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`font-sans ${inter.variable}`}>
          <div className="grid grid-cols-5 grid-rows-5 gap-4">
            <div className="row-span-5">
              <Navbar />
            </div>
            <div className="col-span-4 row-span-5">{children}</div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
